config/routes.rb
Invoicer::Application.routes.draw do
  match 'metrics' => 'metrics#index'
  match 'invoicer' => 'invoicer#index'

  resources :invoice_items

  resources :invoices do
    member do
      get 'submit_invoice'
    end
  end

  resources :customers

  resources :consultants

  root :to => 'invoices#index'

end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
  has_many :invoice_items
  has_many :invoices, :through => :invoice_items

  attr_accessible :default_rate, :email, :name, :title

  validates :name, presence: true, uniqueness: true
  validates :default_rate,
    numericality: { greater_than_or_equal_to: 0},
    allow_nil: true

  def self.options
    all.collect {|c| [c.name, c.id]}
  end

  def total_billables
    invoice_items.inject(0) { |total,item| total+=item.cost }
  end
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  # GET /consultants
  # GET /consultants.json
  def index
    @consultants = Consultant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consultants }
    end
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
    @consultant = Consultant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consultant }
    end
  end

  # GET /consultants/new
  # GET /consultants/new.json
  def new
    @consultant = Consultant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consultant }
    end
  end

  # GET /consultants/1/edit
  def edit
    @consultant = Consultant.find(params[:id])
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new(params[:consultant])

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to @consultant, notice: 'Consultant was successfully created.' }
        format.json { render json: @consultant, status: :created, location: @consultant }
      else
        format.html { render action: "new" }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /consultants/1
  # PUT /consultants/1.json
  def update
    @consultant = Consultant.find(params[:id])

    respond_to do |format|
      if @consultant.update_attributes(params[:consultant])
        format.html { redirect_to @consultant, notice: 'Consultant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant = Consultant.find(params[:id])
    @consultant.destroy

    respond_to do |format|
      format.html { redirect_to consultants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/views/consultants/_form.html.haml
= form_errors @consultant
= form_for @consultant do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :default_rate
    = f.text_field :default_rate
  .actions
    = f.submit 'Save', :class => 'btn'

app/views/consultants/edit.html.haml
%h1 Editing consultant

= render 'form'

= link_to 'Show', @consultant
\|
= link_to 'Back', consultants_path

app/views/consultants/index.html.haml
.page-header
  %h2 Listing Consultants

%table.table
  %tr
    %th Name
    %th Title
    %th Email
    %th Default rate
    %th
    %th
    %th

  - @consultants.each do |consultant|
    %tr
      %td= consultant.name
      %td= consultant.title
      %td= consultant.email
      %td= consultant.default_rate
      %td= link_to 'Show', consultant
      %td= link_to 'Edit', edit_consultant_path(consultant)
      %td= link_to 'Destroy', consultant, method: :delete, data: { confirm: 'Are you sure?' }

%br

.btn= link_to 'New Consultant', new_consultant_path

app/views/consultants/new.html.haml
.page-header
  %h2 New Consultant

= render 'form'

= link_to 'Back', consultants_path

app/views/consultants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @consultant.name
%p
  %b Title:
  = @consultant.title
%p
  %b Email:
  = @consultant.email
%p
  %b Default rate:
  = @consultant.default_rate
%p
  %b Total Billables:
  = @consultant.total_billables
= link_to 'Edit', edit_consultant_path(@consultant)
\|
= link_to 'Back', consultants_path