config/routes.rb
Invoicer::Application.routes.draw do
  match 'metrics' => 'metrics#index'
  match 'invoicer' => 'invoicer#index'

  resources :invoice_items

  resources :invoices do
    member do
      get 'submit_invoice'
    end
  end

  resources :customers

  resources :consultants

  root :to => 'invoices#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :customer
  has_many :consultants, through: :invoice_items
  has_many :invoice_items
  accepts_nested_attributes_for :invoice_items, reject_if: :all_blank, allow_destroy: true

  attr_accessible :customer_id, :desc, :discount, :due_date, :invoice_date, :paid_date, :short_desc, :term, :invoice_items_attributes

  validates :customer_id, presence: true
  validates :short_desc, presence: true
  validates :discount, numericality: { greater_than_or_equal_to: 0,less_than_or_equal_to: 50 }, allow_nil: true
  validates :term, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 90 }, allow_nil: true
  def self.from_address
    CFG[:invoice_from]
  end

  def self.options
    all.collect {|c| ["#{c.id}: #{c.short_desc}", c.id]}
  end

  def invoice_customer(override_date=Date.today)
    unless invoice_items.empty?
      set_invoice_dates(override_date)
      # Call Email to Customer
    else
      false
    end
  end

  def status
    if paid_date
      'Paid'
    elsif due_date && (due_date < Date.today)
      'Overdue'
    elsif due_date && (due_date >= Date.today)
      'Pending'
    else
      'Open'
    end
  end

  def discount_amount
    calculated_discount_amount || 0
  end

  def total_hours
    invoice_items.inject(0) {|total,item| total+=item.hours}
  end

  def total_cost
    invoice_items.inject(0) {|total,item| total+=item.cost}
  end

  def final_cost
    total_cost - discount_amount
  end

  def term_days
    term || customer.default_term || 30
  end
  private
    def calculated_discount_amount
      total_cost * discount/100 if discount
    end

    def set_invoice_dates(override_date)
      self.invoice_date=override_date
      self.due_date=invoice_date + term_days
      save
    end

    def set_final_costs
      self.final_cost=final_cost
      save
    end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  respond_to :html, :json

  def index
    @invoices = Invoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    @invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
    # if @invoice.invoice_items.empty?
    #   @invoice.invoice_items.build
    # end
  end

  # POST /invoices
  # POST /invoices.json
  def create
    customer=params[:invoice].delete :customer_id
    @invoice = Invoice.new(params[:invoice])
    @invoice.customer_id=customer
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def submit_invoice
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      if @invoice.invoice_customer
        format.html { redirect_to invoices_url }
        format.json { render json: @invoice, notice: 'Invoice was successfully submitted.' }
      else
        format.html { redirect_to invoices_url, notice: 'No Invoice Items' }
        format.json { render json: {error: 'No Invoice Items'},status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.haml
= form_errors(@invoice)
= simple_form_for @invoice do |f|
  - if @invoice.new_record?
    = f.association :customer
  = f.input :short_desc, label: 'Short Description'
  = f.input :desc, label: 'Description', input_html: { rows: 4 }
  = f.input :discount
  = f.input :term
  %hr
  %h4 Line Items
  #invoice-items
    %table.table
      %thead
        %tr
          %th Consultant
          %th Desc
          %th Date
          %th Rate
          %th Time
          %th Delete
      %tbody#invoice-items-table
        = f.simple_fields_for :invoice_items do |ii|
          = render 'invoice_item_fields', f: ii
    .links
      = link_to_add_association 'Add Line Item', f, :invoice_items, {class: 'btn', 'data-association-insertion-node' => "tbody#invoice-items-table", 'data-association-insertion-method' => "append"}
  = f.submit 'Save', class: 'btn'
:javascript
  $(document).ready(function(){
    $(".kendo-datepicker").kendoDatePicker({
      format: "yyyy-MM-dd"
    });
    $(".kendo-timepicker").kendoTimePicker({
      format: "HH:mm",
      parse_format: "HH:mm"
    });
    $('#invoice-items').bind('cocoon:after-insert',function(e,added_item){
      $(".kendo-datepicker",added_item).kendoDatePicker({
        value: new Date(),
        format: "yyyy-MM-dd"

      });
      $(".kendo-timepicker",added_item).kendoTimePicker({
        format: "HH:mm",
        parse_format: "HH:mm"
      });
    });
  });

app/views/invoices/_invoice_item_fields.html.haml
%tr.nested-fields
  %td= f.association :consultant, label: false
  %td= f.input :desc, :label => false
  %td= f.input :date, as: :string, label: false,input_html: {class: 'kendo-datepicker'}
  %td= f.input :rate, label: false
  %td= f.input :time, as: :string, label: false, input_html: {class: 'kendo-timepicker'}
  %td= link_to_remove_association "Remove", f, class: 'btn'

app/views/invoices/edit.html.haml
.page-header
  %h2 Editing invoice

= render 'form'

app/views/invoices/index.html.haml
.page-header
  %h1 Listing Invoices

%table.table
  %tr
    %th Invoice #
    %th Desc
    %th Status
    %th Customer
    %th
    %th
    %th

  - @invoices.each do |invoice|
    %tr
      %td= invoice.id
      %td= invoice.short_desc
      %td
        %span.label= invoice.status
      %td= invoice.customer.name
      %td= link_to 'Show', invoice
      %td= link_to 'Edit', edit_invoice_path(invoice)
      %td= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }

%br

.btn= link_to 'New Invoice', new_invoice_path

app/views/invoices/new.html.haml
.page-header
  %h2 New Invoice

= render 'form'

= link_to 'Back', invoices_path

app/views/invoices/show.html.haml
= link_to "<i class='icon-edit'>Edit</i>".html_safe, edit_invoice_path(@invoice), :class => 'btn'
- if @invoice.status == 'Open'
  = link_to "<i class='icon-truck'>Submit Invoice</i>".html_safe, submit_invoice_invoice_path(@invoice), :class => 'btn'
.page-header
  %h2
    ="Invoice #{@invoice.id}"
    %span.label="#{@invoice.status}"
%p.lead
  = @invoice.short_desc
.row
  .span6
    %p
      %strong From:
      %br
      = Invoice.from_address[:name]
      %br
      = Invoice.from_address[:address1]
      %br
      = Invoice.from_address[:city]
      ,
      = Invoice.from_address[:zip]
    %p
      %strong To:
      %br
      = @invoice.customer.name
  .span6
    %p
      %b Invoice date:
      = @invoice.invoice_date
    %p
      %b="Due (Net #{@invoice.term_days}):"
      = @invoice.due_date
%hr
.row
  .span12
    -if @invoice.invoice_items.count > 0
      %table.table
        %thead
          %tr
            %th Consultant
            %th Description
            %th.align-right Rate
            %th.align-right Time (hrs)
            %th.align-right Cost
        %tbody
          - @invoice.invoice_items.each do |ii|
            %tr
              %td=ii.consultant.name
              %td=ii.desc
              %td.align-right=ii.rate
              %td.align-right=ii.hours
              %td.align-right=number_to_currency(ii.cost)
        %tfoot
          %tr
            %td{:colspan => 3} Subtotal
            %td.align-right=@invoice.total_hours
            %td.align-right=number_to_currency(@invoice.total_cost)
          %tr
            %td{:colspan => 4}="Discount: #{@invoice.discount}%"
            %td.align-right=number_to_currency(@invoice.discount_amount)
          %tr
            %td{:colspan => 4} Total
            %td.align-right=number_to_currency(@invoice.final_cost)
    -else
      %h4 Please add invoice items