config/routes.rb
Invoicer::Application.routes.draw do
  match 'metrics' => 'metrics#index'
  match 'invoicer' => 'invoicer#index'

  resources :invoice_items

  resources :invoices do
    member do
      get 'submit_invoice'
    end
  end

  resources :customers

  resources :consultants

  root :to => 'invoices#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :invoices
  has_many :invoice_items, :through => :invoices

  attr_accessible :default_discount, :default_term, :desc, :contact_email, :name, :contact_name

  validates :name, presence: true, uniqueness: true
  validates :default_term,
    numericality: { greater_than_or_equal_to: 1,
      less_than_or_equal_to: 90 },
    allow_nil: true
  validates :default_discount,
    numericality: { greater_than_or_equal_to: 0,
      less_than_or_equal_to: 50 },
    allow_nil: true

  def self.options
    all.collect {|c| [c.name, c.id]}
  end

  def total_billed
    invoice_items.inject(0) { |total,item| total+=item.cost }
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.haml
= form_errors(@customer)
= simple_form_for @customer, :html => {:class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :contact_name, :label => 'Contact Name'
  = f.input :contact_email, :label => 'Contact Email'
  = f.input :desc, :label => 'Company Description'
  = f.input :default_discount, :label => 'Default Discount'
  = f.input :default_term, :label => 'Default Term'
  = f.submit 'Save', :class => 'btn'

app/views/customers/edit.html.haml
%h1 Editing customer

= render 'form'

= link_to 'Show', @customer
\|
= link_to 'Back', customers_path

app/views/customers/index.html.haml
.page-header
  %h1 Customers

%table.table
  %tr
    %th Name
    %th Contact Name
    %th Contact Email
    %th
    %th
    %th

  - @customers.each do |customer|
    %tr
      %td= customer.name
      %td= customer.contact_name
      %td= customer.contact_email
      %td= link_to 'Show', customer
      %td= link_to 'Edit', edit_customer_path(customer)
      %td= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }

%br

.btn= link_to 'New Customer', new_customer_path

app/views/customers/new.html.haml
.page-header
  %h1 New Customer

= render 'form'

= link_to 'Back', customers_path

app/views/customers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @customer.name
%p
  %b Contact Name:
  = @customer.contact_name
%p
  %b Contact Email:
  = @customer.contact_email
%p
  %b Desc:
  = @customer.desc
%p
  %b Default discount:
  = @customer.default_discount
%p
  %b Default term:
  = @customer.default_term
%p
  %b Total Billed:
  = @customer.total_billed
= link_to 'Edit', edit_customer_path(@customer)
\|
= link_to 'Back', customers_path