config/routes.rb
Invoicer::Application.routes.draw do
  match 'metrics' => 'metrics#index'
  match 'invoicer' => 'invoicer#index'

  resources :invoice_items

  resources :invoices do
    member do
      get 'submit_invoice'
    end
  end

  resources :customers

  resources :consultants

  root :to => 'invoices#index'

end

app/models/invoice_item.rb
require 'bigdecimal'
class InvoiceItem < ActiveRecord::Base
  belongs_to :consultant
  # belongs_to :customer
  belongs_to :invoice

  attr_accessible :date, :desc, :item_type_id, :rate, :time, :consultant_id, :consultant

  validates :consultant_id, presence: true
  validates :rate, numericality: { greater_than_or_equal_to: 0}

  def hours
    convert_time_to_hours.round(2)
  end

  def cost
    hours * rate
  end

  private
    def convert_time_to_hours
      time.seconds_since_midnight.to_d/BigDecimal.new(3600)
    end
end

app/controllers/invoice_items_controller.rb
# Note
# Original Intent was to allow Invoice Items to be added seperate from invoice
# but to simplifiy for now I'll take this out.
#
# class InvoiceItemsController < ApplicationController
#   # GET /invoice_items
#   # GET /invoice_items.json
#   def index
#     @invoice_items = InvoiceItem.all

#     respond_to do |format|
#       format.html # index.html.erb
#       format.json { render json: @invoice_items }
#     end
#   end

#   # GET /invoice_items/1
#   # GET /invoice_items/1.json
#   def show
#     @invoice_item = InvoiceItem.find(params[:id])

#     respond_to do |format|
#       format.html # show.html.erb
#       format.json { render json: @invoice_item }
#     end
#   end

#   # GET /invoice_items/new
#   # GET /invoice_items/new.json
#   def new
#     @invoice_item = InvoiceItem.new

#     respond_to do |format|
#       format.html # new.html.erb
#       format.json { render json: @invoice_item }
#     end
#   end

#   # GET /invoice_items/1/edit
#   def edit
#     @invoice_item = InvoiceItem.find(params[:id])
#   end

#   # POST /invoice_items
#   # POST /invoice_items.json
#   def create
#     @invoice_item = InvoiceItem.new(params[:invoice_item])

#     respond_to do |format|
#       if @invoice_item.save
#         format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully created.' }
#         format.json { render json: @invoice_item, status: :created, location: @invoice_item }
#       else
#         format.html { render action: "new" }
#         format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PUT /invoice_items/1
#   # PUT /invoice_items/1.json
#   def update
#     @invoice_item = InvoiceItem.find(params[:id])

#     respond_to do |format|
#       if @invoice_item.update_attributes(params[:invoice_item])
#         format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully updated.' }
#         format.json { head :no_content }
#       else
#         format.html { render action: "edit" }
#         format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /invoice_items/1
#   # DELETE /invoice_items/1.json
#   def destroy
#     @invoice_item = InvoiceItem.find(params[:id])
#     @invoice_item.destroy

#     respond_to do |format|
#       format.html { redirect_to invoice_items_url }
#       format.json { head :no_content }
#     end
#   end
# end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/views/invoice_items/_form.html.haml
= form_errors @invoice_item
= simple_form_for @invoice_item do |f|
  = f.input :desc
  = f.input :date
  = f.input :time, as: time
  = f.input :rate
  = f.input :item_type_id
  = f.submit 'Save', class: 'btn'

app/views/invoice_items/edit.html.haml
.page-header
  %h2 Editing invoice_item
= render 'form'

app/views/invoice_items/index.html.haml
%h1 Listing invoice_items

%table
  %tr
    %th Desc
    %th Date
    %th Item type
    %th Consultant
    %th Customer
    %th Invoice
    %th Rate
    %th
    %th
    %th

  - @invoice_items.each do |invoice_item|
    %tr
      %td= invoice_item.desc
      %td= invoice_item.date
      %td= invoice_item.item_type_id
      %td= invoice_item.consultant_id
      %td= invoice_item.customer_id
      %td= invoice_item.invoice_id
      %td= invoice_item.rate
      %td= link_to 'Show', invoice_item
      %td= link_to 'Edit', edit_invoice_item_path(invoice_item)
      %td= link_to 'Destroy', invoice_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Invoice item', new_invoice_item_path

app/views/invoice_items/new.html.haml
%h1 New invoice_item

= render 'form'

= link_to 'Back', invoice_items_path

app/views/invoice_items/show.html.haml
%p#notice= notice

%p
  %b Desc:
  = @invoice_item.desc
%p
  %b Date:
  = @invoice_item.date
%p
  %b Item type:
  = @invoice_item.item_type_id
%p
  %b Consultant:
  = @invoice_item.consultant_id
%p
  %b Customer:
  = @invoice_item.customer_id
%p
  %b Invoice:
  = @invoice_item.invoice_id
%p
  %b Rate:
  = @invoice_item.rate

= link_to 'Edit', edit_invoice_item_path(@invoice_item)
\|
= link_to 'Back', invoice_items_path